- name: Include distribution specific variables
  include_vars: "{{ ansible_facts.os_family }}.yml"
  tags:
    - nscd
    - nscd-conf

- name: RHEL | Ensure nscd is installed
  yum:
    name: nscd
    state: latest
  when: ansible_pkg_mgr in ['yum', 'dnf']
  tags:
    - nscd

- name: DEBIAN | Ensure nscd is installed
  apt:
    name: nscd
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'
  tags:
    - nscd

- name: Copy nscd.conf
  template:
    src: nscd.conf.j2
    dest: /etc/nscd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nscd
  tags:
    - nscd
    - nscd-conf

- name: Start and enable nscd
  service:
    name: nscd
    enabled: yes
  tags:
    - nscd
